# Load packages
source("R/packages.R")

# ================= DATA PROCESSING =================

#' @description
#' Sort genes by mean expression
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a transposed expression matrix, genes (columns) 
#'    sorted by mean gene expression. The sample/gene orientation is the same as
#'    the input.
sort_expression <- function(counts) {
  dataset_sorted <- counts[, names(sort(colMeans(counts)))]
  return(dataset_sorted)
}

# ================= CO-EXPRESSION ANALYSIS -- BROKEN DOWN =================

#' @description
#' CLR transformation with package "compositions"
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a transposed expression matrix where counts are 
#'    CLR transformed. The sample/gene orientation is the same as the input.
#'    
#' @importFrom compositions clr
#' @importFrom compositions clrInv
get_compositions <- function(counts) {
  run_clr <- compositions::clr(counts)
  clr_proportion <- compositions::clrInv(run_clr)
  return(clr_proportion)
}

#' @description
#' Pearson's correlation coefficient calculation with WGCNA::cor
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a correlation matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise correlation 
#'    coefficient.
#'    
#' @importFrom WGCNA cor
get_pcc <- function(counts) {
  cor_mat <- WGCNA::cor(counts, method = "pearson")
  return(cor_mat)
}

#' @description 
#' Proportionality calculation with package propr
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a similarity matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise proportionality. 
#'    
#' @importFrom propr propr
get_prop <- function(counts) {
  run_propr <- propr(counts,
                     metric = "rho", # rho as proportionality measure
                     ivar = "clr", # clr as selected log-ratio transformation 
                     alpha = NA,
                     p = 100)
  sim_matrix <- getMatrix(run_propr) # extract matrix from propr result
  # putting back matrix column and row names
  colnames(sim_matrix) <- colnames(counts) 
  rownames(sim_matrix) <- colnames(counts)
  return(sim_matrix)
}

#' @description
#' Extracts gene pairs and similarity measures from similarity matrix.
#' @note This function was generated by GPT-5.1.
#' 
#' @param sim_matrix A matrix object of a similarity or correlation matrix. 
#'    Columns and rows are both gene names or locus tags. 
#'
#' @return A data frame of all gene pairs and their similarities with 3 columns:
#'    - gene 1: gene name or locus tag of gene 1 of gene pair
#'    - gene 2: gene name or locus tag of gene 2 of gene pair
#'    - correlation: similarity measure of gene pair
get_genepairs <- function(sim_matrix) {
  # Get lower triangle indices (exclude diagonal) so each gene pair is only
  # extracted once
  idx <- which(lower.tri(sim_matrix, diag = FALSE), arr.ind = TRUE)
  
  # Build data frame of gene pairs and correlations
  corr_df <- data.frame(
    gene1 = rownames(sim_matrix)[idx[, 1]],
    gene2 = colnames(sim_matrix)[idx[, 2]],
    correlation = sim_matrix[idx]
  )
  
  # Sort by descending correlation
  corr_df <- corr_df[order(-corr_df$correlation), ]
  
  return(corr_df)
}

# ================= CORRELATION ANALYSIS FOR BENCHMARKING =================
# GPT 5.2 was used throughout this section for debugging and parsing logic, 
# especially in extracting relevant parts from checkCorBias from 
# COCOLOCUS/COBAIN.
# Mainly, it was used to identify issues with formatting involving row names 
# labeling.
# Functions in this section includes the entire workflow for each method, for
# computational benchmarking.

#' @description
#' Performs the entire "Original" workflow.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#' @param replicates number of replicates per sample in data set
#'
#' @return A matrix object of a correlation matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise correlation 
#'    coefficient.
#'    
#' @importFrom COBAIN logTMM
#' @importFrom COBAIN corAndSpQN
corrs_Original <- function(counts,replicates) {
  # Perform TMM, log transformation, and sort  by mean expression
  tmm <- logTMM(counts,replicates = replicates)
  sorted <- tmm[order(rowMeans(tmm)), ]
  # PCC + SpQN
  means <- stats::setNames(rowMeans(sorted), rownames(sorted))
  corr <- corAndSpQN(sorted,means)
  # Adding back gene names/locus tags
  corr <- corr[rownames(counts), rownames(counts), drop = FALSE]
  message(sprintf("Correlation matrix produced for method 'Original'"))
  return(corr)
}

#' @description
#' Performs the entire "Mean Residuals" workflow.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#' @param replicates number of replicates per sample in data set
#'
#' @return A matrix object of a correlation matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise correlation 
#'    coefficient.
#'    
#' @importFrom COBAIN logTMM
#' @importFrom COBAIN meanResiduals
#' @importFrom COBAIN corAndSpQN
corrs_MeanResiduals <- function(counts,replicates) {
  # Perform TMM, log transformation, and sort  by mean expression
  tmm <- logTMM(counts,replicates = replicates)
  sorted <- tmm[order(rowMeans(tmm)), ]
  # Mean Residuals Transformation
  lemmed <- meanResiduals(sorted)
  mr <- lemmed[rownames(sorted), ]
  # PCC + SpQN
  means <- stats::setNames(rowMeans(sorted), rownames(sorted))
  corr <- corAndSpQN(mr,means)
  # Adding back gene names/locus tags
  corr <- corr[rownames(counts), rownames(counts), drop = FALSE]
  message(sprintf("Correlation matrix produced for method 'MeanResiduals'"))
  return(corr)
}

#' @description
#' Performs the entire "PC1 Residuals" workflow.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#' @param replicates number of replicates per sample in data set
#'
#' @return A matrix object of a correlation matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise correlation 
#'    coefficient.
#'    
#' @importFrom COBAIN logTMM
#' @importFrom COBAIN removePCs
#' @importFrom COBAIN corAndSpQN
corrs_PC1Residuals <- function(counts,replicates) {
  # Perform TMM, log transformation, and sort  by mean expression
  tmm <- logTMM(counts,replicates = replicates)
  sorted <- tmm[order(rowMeans(tmm)), ]
  # PC1 Residuals Transformation
  less_pc <- suppressMessages(removePCs(sorted, 1))
  means <- stats::setNames(rowMeans(sorted), rownames(sorted))
  pc1 <- less_pc[rownames(sorted), ]
  corr <- corAndSpQN(pc1,means)
  corr <- corr[rownames(counts), rownames(counts), drop = FALSE]
  message(sprintf("Correlation matrix produced for method 'PC1Residuals'"))
  return(corr)
}

#' @description
#' Performs the entire "CLR" workflow.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a correlation matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise correlation 
#'    coefficient.
#'    
#' @importFrom zCompositions cmultRepl
corrs_CLR <- function(counts) {
  counts_t <- t(counts) 
  counts_sorted <- sort_expression(counts_t) 
  z_counts <- cmultRepl(counts_sorted,method = "CZM",output="p-counts") 
  comp <- get_compositions(z_counts)
  comp_pcc <- get_pcc(comp)
  message(sprintf("Correlation matrix produced for method 'CLR'"))
  return(comp_pcc)
}

#' @description
#' Performs the entire "propr" workflow.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a similarity matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise proportionality.
get_propr <- function(counts) {
  counts_t <- t(counts) 
  counts_sorted <- sort_expression(counts_t) 
  pr <- get_prop(counts_sorted)
  message(sprintf("Similarity matrix produced for method 'propr'"))
  return(pr)
}

#' @description
#' Performs the entire "propr + zCompositions" workflow.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#'
#' @return A matrix object of a similarity matrix. Columns and rows are both
#'    gene names or locus tags, and maps to their pairwise proportionality.
#'    
#' @importFrom zCompositions cmultRepl
get_zpropr <- function(counts) {
  counts_t <- t(counts) 
  counts_sorted <- sort_expression(counts_t)
  z_counts <- cmultRepl(counts_sorted,method = "CZM",output="p-counts")
  pr_z <- get_prop(z_counts)
  message(sprintf("Similarity matrix produced for method 'propr + zCompositions'"))
  return(pr_z)
}

# ================= COMBINED METHODS =================
# GPT 5.2 was used here for debugging and parsing logic, especially in 
# extracting relevant parts from checkCorBias from COCOLOCUS/COBAIN. 

#' @description
#' Single function that performs all co-expression analysis workflows and 
#' produces the similarity matrices and extracts the sorted gene pairs.
#' 
#' @param counts A matrix object of a transposed expression matrix, such that
#'    Rows = Conditions or samples
#'    Columns = Genes or locus tags
#' @param replicates number of replicates per sample in data set
#'
#' @return A list of lists, containing matrices and gene pairs. 
#'    matrix: A list of matrices, containing similarity matrices produced by 
#'            each method. Row and column names are genes/locus tags.
#'    genepairs: A list of data frames produced by each method, containing gene 
#'            pairs and their similarities with 3 columns:
#'            - gene 1: gene name or locus tag of gene 1 of gene pair
#'            - gene 2: gene name or locus tag of gene 2 of gene pair
#'            - correlation: similarity measure of gene pair
#'    
#' @importFrom zCompositions cmultRepl
coexpr_analysis <- function(counts, replicates) {
  # Basic processing
  counts_t <- t(counts) # Transpose
  counts_sorted <- sort_expression(counts_t) # Sorting genes by mean expression
  # zCompositions zero imputation
  z_counts <- cmultRepl(counts_sorted,method = "CZM",output="p-counts") 
  
  # CLR
  comp <- get_compositions(z_counts)
  comp_pcc <- get_pcc(comp)
  message(sprintf("Correlation matrix produced for method 'CLR'"))
  # propr methods
  pr <- suppressMessages(get_prop(counts_sorted))
  message(sprintf("Similarity matrix produced for method 'propr'"))
  pr_z <- suppressMessages(get_prop(z_counts))
  message(sprintf("Similarity matrix produced for method 'propr + zCompositions'"))
  
  # TMM and log-transformation, and sorting by mean expression
  tmm <- logTMM(counts,replicates = replicates)
  sorted <- tmm[order(rowMeans(tmm)), ]
  # Mean Residuals transformation
  lemmed <- meanResiduals(sorted) 
  # PC1 Residuals transformation
  less_pc <- suppressMessages(removePCs(sorted, 1))
  
  # Combining results of COBAIN/COCOLOCUS methods to return row name labels 
  # together. Logic was retained from checkCorBias.ChatGPT was used here to 
  # understand and apply data processing. 
  results <- list(Original = sorted, 
                  MeanResiduals = lemmed, 
                  PC1Residuals = less_pc)
  results <- lapply(results, function(x) x[rownames(counts), ])
  
  # Calculating PCC and SpQN for COCOLOCUS/COBAIN methods
  means <- stats::setNames(rowMeans(sorted), rownames(sorted))
  corr_og <- corAndSpQN(results$Original,means)
  message(sprintf("Correlation matrix produced for method 'Original'"))
  corr_mr <- corAndSpQN(results$MeanResiduals, means)
  message(sprintf("Correlation matrix produced for method 'MeanResiduals'"))
  corr_pc1 <- corAndSpQN(results$PC1Residuals, means)
  message(sprintf("Correlation matrix produced for method 'PC1Residuals'"))
  
  # Compiling outputs
  # All matrices
  matrix <- list()
  matrix$Original = corr_og
  matrix$MeanResiduals = corr_mr
  matrix$PC1Residuals = corr_pc1
  matrix$CLR = comp_pcc
  matrix$propr = pr
  matrix$propr_z = pr_z
  
  # All gene pairs
  genepairs <- list()
  genepairs$Original = get_genepairs(corr_og)
  genepairs$MeanResiduals = get_genepairs(corr_mr)
  genepairs$PC1Residuals = get_genepairs(corr_pc1)
  genepairs$CLR = get_genepairs(comp_pcc)
  genepairs$propr = get_genepairs(pr)
  genepairs$propr_z = get_genepairs(pr_z)
  
  output <- list(matrix = matrix, genepairs = genepairs)
  
  return(output)
}

